#!/bin/bash

# ----------SCRIPT INFO-----------
#
# 완료 날짜 : 2016/09/17
# 최종 수정날짜: 2019/12/30
# 설명: 플랫폼 설치 자동화를 실행한다.
# 전제 조건: 플랫폼 설치 자동화가 설치되어 있어야 한다.
#
# ----------SCRIPT INFO-----------

set -e -x
cd -P ~/OPENPAAS-IEDA-WEB-5.0/OPENPAAS-IEDA-CONTROLLER/
java -jar -Xms3072m -Xmx3072m -Djava.security.egd=file:/dev/./urandom -Dspring.config.location=./application.properties target/OPENPAAS-IEDA-WEB-CONTROLLER-1.0.0--CONTROLLER-SNAPSHOT.jar >> /var/log/deployer/deployer.log 2>&1
